### ISSUE TITLE
Tags and verison information mismatch

### ISSUE THREAD

**Issue by ghost** [aario/snotepad#1]
While you have tagged new "versions", the Android system still recognizes this as version name "1.0" with versioncode 1, see `app/build.gradle`. The name is a simple user facing string without any meaning applied. The code is an integer that is used to check if the app is an update or not. See https://developer.android.com/studio/publish/versioning.html.

**Comment by aario** [comment]
Thanks for the comment. Will fix it and make another release this time with current versioning.

**Comment by aario** [comment]
Done.
