### ISSUE TITLE
[Bug] Save icon obfuscates note contents

### ISSUE THREAD

**Issue by muleyryan** [aario/snotepad#16]
I notice that when I'm typing, the save icon will occlude the contents of what I type. A workaround might be to make the button more transparent, or to move it where the Undo and Redo buttons are.

**Comment by latach** [comment]
This issue has already be resolved. Please download version 1.2.2 from here:

https://github.com/aario/snotepad/releases/download/1.2.2/app-release.apk

Please note that the version available on _F-Droid_ is 1.2.1.

**Comment by muleyryan** [comment]
Awesome. Closing.
