### ISSUE TITLE
owncloud address

### ISSUE THREAD

**Issue by fadiphi** [aario/snotepad#3]
in Select Folder it seems impossible to put an Owncloud address in order to sync notes

**Comment by aario** [comment]
By putting Owncloud address I mean address of your owncloud folder on your phone's memory. Something like:
/storage/emulated/0/owncloud/admin@myowncloudwebsite.com/Documents/Notes
Actually you're owncloud app has a folder on your phone's memory where it downloads it files to and uploads its files from. You have to select that so you're notes stay within you're owncloud apps control. You can later go to owncloud app and select your note and synchronize them. Please let me know if you still had problem.
