### ISSUE TITLE
Improve scrolling

### ISSUE THREAD

**Issue by ghost** [aario/snotepad#6]
I'm running version 1.2.1.

The scrolling needs enhancement. I.e the quicker you scroll across the screen; the quicker it should scroll up/down.

Currently, scrolling follows the finger, and when the finger is lifted off the screen; scrolling stops instantly. It should be similar to scrolling in the Settings application.

**Comment by ioctl-user** [comment]
I would like to add a good example of this feature in the similar programm:
https://f-droid.org/repository/browse/?fdid=org.paulmach.textedit

In that editor scrolling allow quick list through even big files. Note, that this programm is old and doesn't work properly in modern Androids.

**Comment by aario** [comment]
Thanks for reporting. Done.
