### ISSUE TITLE
Problems with landscape format and ideas for development

### ISSUE THREAD

**Issue by lucchinelli** [aario/snotepad#8]
Hi Aario.
I am using the latest version (1.2.1) of your program from fdroid. If l write a note and the sentence is to long I will switch from portait to landscape format by turn the phone then your snotepad crashes. You can start it again with no problems but in the same situation the program crashes again.
I use a Honor 4x with OS 4.4.2 phone. I hope you can fix this. In summary I find your program is very nice to use it for short notes.
A idea for future development:
A “sent to“ menu for the files would be very nice. So you can sent the notes on whatsapp for example. 
Thanks it advance
Marco

**Comment by Natenom** [comment]
Same here when changing to landscape/portrait format.

**Comment by aario** [comment]
Thanks for reporting. Done.
